[package]
name = "madoka_auth"
version = "0.1.0-alpha"
edition = "2021"

[lib]
name = "madoka_auth_lib"

[dependencies]
axum = "0.7"
log = "0.4.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
